export const COMMON = {
	TOAST_SHOW: "TOAST_SHOW",
};


export const PRODUCT = {
	PRODUCT_CREATE: "PRODUCT_CREATE",
	// PRODUCT_CREATE_SUCCEESS: "PRODUCT_CREATE",

	PRODUCT_READ_LIST: "PRODUCT_READ_LIST",
	PRODUCT_READ_LIST_SUCCESS: "PRODUCT_READ_LIST_SUCCESS"
}